---
- hosts: kibana
  become: yes
  vars_files:
    - "../vars/elasticsearch.yml"
  tasks:
  - name: Remove apt lock file
    file:
      state: absent
      path: "{{ item }}"
    loop: [ '/var/lib/dpkg/lock-frontend', '/var/lib/dpkg/lock']

  - name: Install required system packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common' ]

  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce, docker-ce-cli, containerd.io
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

  - name: Install Python
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: [ 'python3-pip', 'python3-setuptools' ]

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Install or upgrade docker-compose
    get_url:
      url : https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: "a+x"
      force: yes

  - name: Copy docker-compose.yml
    copy:
      src: ../files/kibana
      dest: ~/
      mode: preserve
