version: '3.7'

services:
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.5.0
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: /var/log/
        target: /var/log/
        read_only: true
    user: root
    networks:
      - elk

networks:
  elk:

volumes:
  filebeat:
