version: '3.7'

services:
  kibana:
    container_name: kibana
    image: kibana:8.5.0
    volumes:
      - type: bind
        source: ./kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:

volumes:
  kibana:

