version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.0
    volumes:
      - type: bind
        source: ./elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: password
      KIBANA_PASSWORD: password
      discovery.type: single-node
    networks:
      - elk

#  logstash:
#   container_name: logstash
#   image: logstash:8.5.0
#    volumes:
#     - type: bind
#        source: ./logstash.yml
#        target: /usr/share/logstash/config/logstash.yml
#        read_only: true
#      - type: bind
#        source: ./pipeline
#        target: /usr/share/logstash/pipeline
#        read_only: true
#    ports:
#      - "5044:5044"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

networks:
  elk:

volumes:
  elasticsearch:

